"""empty message

Revision ID: e463b09b2315
Revises: 49977fcbb961
Create Date: 2024-07-21 20:30:15.615146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e463b09b2315'
down_revision: Union[str, None] = '49977fcbb961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ID', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Birth', sa.Date(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Gender', sa.Integer(), nullable=False),
    sa.Column('PpojakCoin', sa.Integer(), nullable=False),
    sa.Column('ProfileName', sa.String(), nullable=False),
    sa.Column('ProfileComment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    # ### end Alembic commands ###
